from django.db import models
from django.conf import settings
import uuid
SPECIALITY_CHOICES = [
    ('Accountant', 'accountant'),
    ('Actor', 'actor'),
    ('Actuary', 'actuary'),
    ('Architect', 'architect'),
    ('Artist', 'artist'),
    ('Astronomer', 'astronomer'),
    ('Athlete', 'athlete'),
    ('Audiologist', 'audiologist'),
    ('Biologist', 'biologist'),
    ('Botanist', 'botanist'),
    ('Chef', 'chef'),
    ('Chemist', 'chemist'),
    ('Coach', 'coach'),
    ('Comedian', 'comedian'),
    ('Computer Scientist', 'computer_scientist'),
    ('Consultant', 'consultant'),
    ('Dancer', 'dancer'),
    ('Data Analyst', 'data_analyst'),
    ('Data Scientist', 'data_scientist'),
    ('Dentist', 'dentist'),
    ('Designer', 'designer'),
    ('Developer', 'developer'),
    ('Doctor', 'doctor'),
    ('Economist', 'economist'),
    ('Editor', 'editor'),
    ('Electrician', 'electrician'),
    ('Engineer', 'engineer'),
    ('Entrepreneur', 'entrepreneur'),
    ('Farmer', 'farmer'),
    ('Film Director', 'film_director'),
    ('Financial Analyst', 'financial_analyst'),
    ('Firefighter', 'firefighter'),
    ('Geologist', 'geologist'),
    ('Graphic Designer', 'graphic_designer'),
    ('Hairdresser', 'hairdresser'),
    ('Historian', 'historian'),
    ('Illustrator', 'illustrator'),
    ('Interpreter', 'interpreter'),
    ('IT Specialist', 'it_specialist'),
    ('Journalist', 'journalist'),
    ('Lawyer', 'lawyer'),
    ('Librarian', 'librarian'),
    ('Mechanic', 'mechanic'),
    ('Marketing Specialist', 'marketing_specialist'),
    ('Mathematician', 'mathematician'),
    ('Model', 'model'),
    ('Musician', 'musician'),
    ('Nurse', 'nurse'),
    ('Nutritionist', 'nutritionist'),
    ('Painter', 'painter'),
    ('Photographer', 'photographer'),
    ('Pharmacist', 'pharmacist'),
    ('Pilot', 'pilot'),
    ('Physician', 'physician'),
    ('Physicist', 'physicist'),
    ('Plumber', 'plumber'),
    ('Police Officer', 'police_officer'),
    ('Politician', 'politician'),
    ('Professor', 'professor'),
    ('Psychologist', 'psychologist'),
    ('Receptionist', 'receptionist'),
    ('Researcher', 'researcher'),
    ('Sales Manager', 'sales_manager'),
    ('Scientist', 'scientist'),
    ('Security Specialist', 'security_specialist'),
    ('Singer', 'singer'),
    ('Software Engineer', 'software_engineer'),
    ('Statistician', 'statistician'),
    ('Surgeon', 'surgeon'),
    ('Teacher', 'teacher'),
    ('Translator', 'translator'),
    ('Veterinarian', 'veterinarian'),
    ('Writer', 'writer'),
    ('Yoga Instructor', 'yoga_instructor'),
    ('Zoologist', 'zoologist'),
    ('Actress', 'actress'),
    ('Animator', 'animator'),
    ('Archaeologist', 'archaeologist'),
    ('Astronaut', 'astronaut'),
    ('Baker', 'baker'),
    ('Barista', 'barista'),
    ('Bartender', 'bartender'),
    ('Biochemist', 'biochemist'),
    ('Blacksmith', 'blacksmith'),
    ('Bricklayer', 'bricklayer'),
    ('Bus Driver', 'bus_driver'),
    ('Carpenter', 'carpenter'),
    ('Cartographer', 'cartographer'),
    ('Chef de Cuisine', 'chef_de_cuisine'),
    ('Choreographer', 'choreographer'),
    ('Civil Engineer', 'civil_engineer'),
    ('Coach Trainer', 'coach_trainer'),
    ('Composer', 'composer'),
    ('Computer Programmer', 'computer_programmer'),
    ('Construction Worker', 'construction_worker'),
    ('Content Writer', 'content_writer'),
    ('Copywriter', 'copywriter'),
    ('Curator', 'curator'),
    ('Dietetics Specialist', 'dietetics_specialist'),
    ('Director', 'director'),
    ('Econometrics Specialist', 'econometrics_specialist'),
    ('Editor-in-Chief', 'editor_in_chief'),
    ('Electrical Engineer', 'electrical_engineer'),
    ('Event Planner', 'event_planner'),
    ('Fashion Designer', 'fashion_designer'),
    ('Film Editor', 'film_editor'),
    ('Financial Planner', 'financial_planner'),
    ('Fitness Trainer', 'fitness_trainer'),
    ('Florist', 'florist'),
    ('Geographer', 'geographer'),
    ('Gym Instructor', 'gym_instructor'),
    ('Handyman', 'handyman'),
    ('HR Specialist', 'hr_specialist'),
    ('Illustration Artist', 'illustration_artist'),
    ('Industrial Designer', 'industrial_designer'),
    ('Interior Designer', 'interior_designer'),
    ('IT Consultant', 'it_consultant'),
    ('Judge', 'judge'),
    ('Laboratory Technician', 'laboratory_technician'),
    ('Landscaper', 'landscaper'),
    ('Linguist', 'linguist'),
    ('Makeup Artist', 'makeup_artist'),
    ('Marine Biologist', 'marine_biologist'),
    ('Mechanics Engineer', 'mechanics_engineer'),
    ('Meteorologist', 'meteorologist'),
    ('Microbiologist', 'microbiologist'),
    ('Network Engineer', 'network_engineer'),
    ('Nutrition Consultant', 'nutrition_consultant'),
    ('Occupational Therapist', 'occupational_therapist'),
    ('Oceanographer', 'oceanographer'),
    ('Optician', 'optician'),
    ('Painter Artist', 'painter_artist'),
    ('Paralegal', 'paralegal'),
    ('Paramedic', 'paramedic'),
    ('Philosopher', 'philosopher'),
    ('Photographic Artist', 'photographic_artist'),
    ('Physical Therapist', 'physical_therapist'),
    ('Pilot Captain', 'pilot_captain'),
    ('Plant Scientist', 'plant_scientist'),
    ('Poet', 'poet'),
    ('Political Analyst', 'political_analyst'),
    ('Producer', 'producer'),
    ('Professor of Science', 'professor_of_science'),
    ('Program Manager', 'program_manager'),
    ('Project Engineer', 'project_engineer'),
    ('Public Relations Specialist', 'public_relations_specialist'),
    ('Quality Analyst', 'quality_analyst'),
    ('Radiologist', 'radiologist'),
    ('Real Estate Agent', 'real_estate_agent'),
    ('Reception Manager', 'reception_manager'),
    ('Research Analyst', 'research_analyst'),
    ('Robotics Engineer', 'robotics_engineer'),
    ('Sculptor', 'sculptor'),
    ('SEO Specialist', 'seo_specialist'),
    ('Social Worker', 'social_worker'),
    ('Software Developer', 'software_developer'),
    ('Sound Engineer', 'sound_engineer'),
    ('Statistician Analyst', 'statistician_analyst'),
    ('Strategy Consultant', 'strategy_consultant'),
    ('Structural Engineer', 'structural_engineer'),
    ('Surveyor', 'surveyor'),
    ('Teacher Assistant', 'teacher_assistant'),
    ('Technical Writer', 'technical_writer'),
    ('Television Presenter', 'television_presenter'),
    ('UX Designer', 'ux_designer'),
    ('UI Designer', 'ui_designer'),
    ('Veterinary Nurse', 'veterinary_nurse'),
    ('Video Editor', 'video_editor'),
    ('Visual Designer', 'visual_designer'),
    ('Web Developer', 'web_developer'),
    ('Writer Editor', 'writer_editor'),
    ('Yoga Teacher', 'yoga_teacher'),
    ('Youth Worker', 'youth_worker'),
    ('Zoology Specialist', 'zoology_specialist'),
]
class Resume(models.Model):
    name=models.CharField(max_length=100)
    surname=models.CharField(max_length=100)
    father_name=models.CharField(max_length=100)
    email=models.EmailField(max_length=100, unique=True)
    experience=models.CharField(max_length=100)
    education=models.CharField(max_length=100)
    image=models.ImageField(upload_to='images/', blank=True, null=True)
    speciality=models.CharField(max_length=100,choices=SPECIALITY_CHOICES)
    created_at=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    def __str__(self):
        return self.name