# Generated by Django 5.2.7 on 2026-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='speciality',
            field=models.CharField(choices=[('finansist', 'Finansist'), ('architecture', 'Architecture'), ('Sales manager', 'Sales Manager'), ('Sportsman', 'Sportsman'), ('Programmer', 'Programmer')], max_length=100),
        ),
    ]
