# Generated by Django 5.2.7 on 2026-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_resume_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='telephone',
            field=models.CharField(),
        ),
    ]
