# Generated by Django 5.2.7 on 2026-03-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_resume_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
