# Generated by Django 6.0.3 on 2026-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_resume_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
