# Generated by Django 5.2.7 on 2026-03-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_emailverificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
