# Generated by Django 5.2.7 on 2026-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='speciality',
            field=models.CharField(choices=[('finansist', 'Finansist'), ('architecture', 'Architecture'), ('sales_manager', 'Sales Manager'), ('sportsman', 'Sportsman'), ('programmer', 'Programmer'), ('doctor', 'Doctor'), ('lawyer', 'Lawyer'), ('teacher', 'Teacher'), ('engineer', 'Engineer'), ('designer', 'Designer'), ('accountant', 'Accountant'), ('psychologist', 'Psychologist'), ('pharmacist', 'Pharmacist'), ('journalist', 'Journalist'), ('marketing_specialist', 'Marketing Specialist'), ('data_scientist', 'Data Scientist'), ('project_manager', 'Project Manager'), ('nurse', 'Nurse'), ('chef', 'Chef'), ('electrician', 'Electrician'), ('translator', 'Translator'), ('economist', 'Economist'), ('biologist', 'Biologist'), ('photographer', 'Photographer'), ('security_specialist', 'Security Specialist')], max_length=100),
        ),
    ]
