# Generated by Django 5.2.7 on 2026-03-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_alter_resume_speciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
