# Generated by Django 5.2.7 on 2026-03-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_resume_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='telephone',
        ),
    ]
